import {ReactNode} from "react";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import {Navbar} from "@/components";
import {ResourceProvider} from "@/contexts";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
            <ResourceProvider>
                <div className="h-screen text-black">
                    <div className="fixed top-0 left-0 w-screen h-screen bg-[#f5f2f1] -z-10"></div>
                    <Navbar/>
                    {children}
                </div>
            </ResourceProvider>
        </Providers>
        </body>
        </html>
);
}
